// Regenerates src/assets.ts from the PNG sources in site/.
//
// The bridge serves its own icons and share image so that a self-hosted
// instance is complete on its own, without a reverse proxy configured to
// serve static files beside it. They are inlined rather than read from disk
// because the published package runs from dist/, and a compiled build has no
// reason to carry a file tree it would then have to locate at runtime.
//
// Run with: npm run assets:build
import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import path from 'node:path'

const root = path.join(import.meta.dirname, '..')
const assets = [
  { name: 'FAVICON_PNG', file: 'favicon.png' },
  { name: 'APPLE_TOUCH_ICON_PNG', file: 'apple-touch-icon.png' },
  { name: 'SHARE_IMAGE_PNG', file: 'og.png' },
]

const wrap = (base64) => (base64.match(/.{1,96}/g) ?? []).join('\n')

const body = assets
  .map(({ name, file }) => {
    const bytes = readFileSync(path.join(root, 'site', file))
    return `// site/${file}, ${bytes.length} bytes\nexport const ${name} = Buffer.from(\n  \`${wrap(bytes.toString('base64'))}\`.replace(/\\n/g, ''),\n  'base64',\n)`
  })
  .join('\n\n')

const out = path.join(root, 'src', 'assets.ts')
writeFileSync(
  out,
  `// Generated by scripts/build-assets.mjs from site/. Do not edit by hand.\n// Regenerate with: npm run assets:build\n\n${body}\n`,
)

// Generated or not, it is linted with everything else, so let the formatter
// settle the layout rather than trying to emit it byte-perfect from here.
execFileSync('npx', ['biome', 'check', '--write', out], { cwd: root, stdio: 'pipe' })

console.log(`wrote src/assets.ts from ${assets.length} files`)
